services:
  demo:
    build: ./leshanDemoServer
    # Internal networking only - no direct port exposure
    expose:
      - "8080"
      - "5683/udp"

  bootstrap:
    build: ./bootstrapServer
    # Internal networking only - no direct port exposure
    expose:
      - "8080"
      - "5684/udp"

  encore:
    image: tony300/my-encore-demo:1.2
    env_file:
      - ./.env
    ports:
      - "4000:8080"
    depends_on:
      - demo
      - bootstrap
    command: ["encore", "run"]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"            # HTTP
      - "5683:5683/udp"     # CoAP UDP port
      - "5684:5684/udp"     # Bootstrap CoAP UDP port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - demo
      - bootstrap
